server {
    listen 80;
    server_name  dswebapnahai.shop www.dswebapnahai.shop;   # OR use your public IP

    # Increase upload size (important for image uploads)
    client_max_body_size 128M;
    resolver 127.0.0.11 valid=10s;
    set $upstream http://app:3000;
    location / {
        proxy_pass $upstream;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
    # Optional: health check
    #location /health {
    #    access_log off;
    #    return 200 "OK\n";
    #}

    #listen 443 ssl; # managed by Certbot
    #ssl_certificate /etc/letsencrypt/live/dswebapnahai.shop/fullchain.pem; # managed by Certbot
    #ssl_certificate_key /etc/letsencrypt/live/dswebapnahai.shop/privkey.pem; # managed by Certbot
    #include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    #ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

#}
#server {
#    if ($host = dswebapnahai.shop) {
#        return 301 https://$host$request_uri;
#    } # managed by Certbot


#    listen 80;
#    server_name dswebapnahai.shop;
#    return 404; # managed by Certbot


#}
