name: Automated EC2 Deployment

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
	    cd /home/ubuntu/Nodejs
            git pull origin main
            
            # 1. Build the image locally on the EC2 server
            docker build -t node-app:latest .
            
            # 2. Deploy or update the Swarm Stack using the new image
            docker stack deploy -c docker-compose.yml production_stack
            
            # 3. Clean up old images
            docker image prune -f
